import streamlit as st
import pandas as pd
import time
from datetime import datetime
import os
import base64
import plotly.graph_objects as go

# --- SAFE FPDF IMPORT FOR REPORT GENERATION ---
try:
    from fpdf import FPDF

    FPDF_AVAILABLE = True
except ImportError:
    FPDF_AVAILABLE = False

# --- 1. UI CONFIGURATION & THEME ---
st.set_page_config(page_title="LEEP-2026 Eligibility Simulator", page_icon="🎓", layout="wide")

# Columns for Language Selection
col_hdr, col_lang = st.columns([5, 1.2])
with col_lang:
    selected_language = st.selectbox(
        "🌐 Language / भाषा चुनें",
        ["English", "हिन्दी (Hindi)"],
        index=0,
        help="Switch interface language / इंटरफ़ेस भाषा बदलें"
    )

is_hindi = (selected_language == "हिन्दी (Hindi)")

# Hardcoded Theme Variables for Light Mode Navy Default
theme_axis_color = "#31333F"
chart_theme = None
navy_blue = "#1E3A8A"
navy_hover = "#1E40AF"

# --- 2. TRANSLATION DICTIONARY (BILINGUAL ENGINE) ---
T = {
    "app_title": "LEEP" if not is_hindi else "लीप",
    "app_subtitle": "LATERAL ENTRY ENGINEERING PROGRAMME • ELIGIBILITY SIMULATOR" if not is_hindi else "लेटरल एंट्री इंजीनियरिंग प्रवेश • पात्रता सिम्युलेटर",
    "disclaimer_title": "OFFICIAL DISCLAIMER:" if not is_hindi else "आधिकारिक अस्वीकरण (Disclaimer):",
    "disclaimer_text": (
        "This Eligibility Simulator is provided for informational and guidance purposes only. The projected priority tiers and "
        "effective scores generated by this tool are tentative and based entirely on the unverified data "
        "entered by the candidate. The final, official merit list will be generated by the Centre for Electronic Governance (CEG) "
        "during the actual LEEP-2026 Centralized Admission Process."
    ) if not is_hindi else (
        "यह पात्रता सिम्युलेटर केवल सूचनात्मक और मार्गदर्शन उद्देश्यों के लिए प्रदान किया गया है। इस टूल द्वारा उत्पन्न अनुमानित प्राथमिकता "
        "स्तर और प्रभावी अंक पूरी तरह से अनंतिम (tentative) हैं। अंतिम, आधिकारिक योग्यता सूची वास्तविक LEEP-2026 प्रवेश प्रक्रिया "
        "के दौरान सेंटर फॉर इलेक्ट्रॉनिक गवर्नेंस (CEG) द्वारा ही जारी की जाएगी।"
    ),
    "eval_details_header": "📋 Candidate Evaluation Details" if not is_hindi else "📋 अभ्यर्थी मूल्यांकन विवरण",
    "step1_title": "🎓 Step 1: Academic Information" if not is_hindi else "🎓 चरण 1: शैक्षणिक जानकारी",
    "cand_name": "Candidate Name" if not is_hindi else "अभ्यर्थी का नाम",
    "dob": "Date of Birth" if not is_hindi else "जन्म तिथि",
    "dob_help": "Used as the primary tie-breaker. Older candidates rank higher." if not is_hindi else "प्राथमिक टाई-ब्रेकर के रूप में उपयोग किया जाता है। अधिक आयु वाले अभ्यर्थी को उच्च रैंक मिलती है।",

    # LEEP Specific Academic Strings
    "qual_basis": "Qualifying Degree/Diploma" if not is_hindi else "अर्हक डिग्री/डिप्लोमा",
    "perc_qual": "Qualifying Exam Overall (%)" if not is_hindi else "अर्हक परीक्षा कुल (%)",
    "cutoff_help": "Eligibility cutoff is 45% (GEN) or 40% (Reserved)." if not is_hindi else "पात्रता कटऑफ 45% (सामान्य) या 40% (आरक्षित) है।",

    "passed_bter": "Passed Diploma from BTER, Jodhpur?" if not is_hindi else "क्या BTER, जोधपुर से डिप्लोमा उत्तीर्ण किया है?",
    "math_12th": "Passed 10+2 with Mathematics?" if not is_hindi else "क्या 10+2 गणित विषय के साथ उत्तीर्ण किया है?",
    "allied_sector": "Degree is in the Same/Allied Sector?" if not is_hindi else "क्या डिग्री समान/संबद्ध क्षेत्र में है?",

    # Demographics & Priority
    "step2_title": "🌍 Step 2: Domicile & Base Category" if not is_hindi else "🌍 चरण 2: मूल निवास और श्रेणी",
    "gender": "Gender" if not is_hindi else "लिंग",
    "base_cat": "Base Category" if not is_hindi else "मूल श्रेणी",
    "area": "Area Type" if not is_hindi else "क्षेत्र का प्रकार",
    "domicile": "Domicile State" if not is_hindi else "मूल निवास (Domicile)",
    "priority_help": "Your domicile and qualifying exam type determine your LEEP Priority Tier." if not is_hindi else "आपका मूल निवास और अर्हक परीक्षा का प्रकार आपके LEEP प्राथमिकता स्तर को निर्धारित करते हैं।",

    # Quotas
    "step3_title": "⭐ Step 3: Quotas & Horizontal Reservations" if not is_hindi else "⭐ चरण 3: कोटा और क्षैतिज आरक्षण",
    "pwd_label": "Person with Special Ability (PwD)" if not is_hindi else "विशेष योग्यजन (PwD)",
    "tfws_label": "Income < ₹8.00 Lakhs (TFWS)" if not is_hindi else "आय < ₹8.00 लाख (TFWS)",
    "km_label": "Kashmiri Migrant (KM)" if not is_hindi else "कश्मीरी प्रवासी (KM)",
    "km_help": "Enforces Unreserved (GEN) base category." if not is_hindi else "अनारक्षित (GEN) मूल श्रेणी लागू करता है।",
    "exs_label": "Ex-Servicemen (EXS)" if not is_hindi else "भूतपूर्व सैनिक (EXS)",
    "sports_label": "Valid Sports Quota" if not is_hindi else "वैध खेल कोटा (Sports Quota)",
    "sports_cat_label": "Sports Category" if not is_hindi else "खेल श्रेणी (Sports Category)",
    "widow_label": "Widow / Divorced" if not is_hindi else "विधवा / तलाकशुदा",
    "single_woman_label": "Single Woman Dependent" if not is_hindi else "एकल महिला के आश्रित",

    # UI Text
    "submit_btn": "🚀 Run LEEP Eligibility Simulator" if not is_hindi else "🚀 लीप पात्रता सिम्युलेटर चलाएं",
    "toast_done": "Eligibility Calculation Completed!" if not is_hindi else "पात्रता गणना पूरी हुई!",
    "dashboard_title": "📊 Candidate Eligibility Dashboard" if not is_hindi else "📊 अभ्यर्थी पात्रता डैशबोर्ड",

    "disq_cutoff": "### ❌ Disqualified: Failed Minimum Eligibility" if not is_hindi else "### ❌ अपात्र: न्यूनतम पात्रता विफल",
    "disq_math": "### ❌ Disqualified: Missing Subject" if not is_hindi else "### ❌ अपात्र: विषय अनुपलब्ध",
    "disq_math_msg": "B.Sc. candidates must have passed 10+2 with Mathematics." if not is_hindi else "B.Sc. उम्मीदवारों को 10+2 गणित विषय के साथ उत्तीर्ण करना अनिवार्य है।",
    "disq_allied": "### ❌ Disqualified: Sector Mismatch" if not is_hindi else "### ❌ अपात्र: क्षेत्र बेमेल",
    "disq_allied_msg": "B.Voc/D.Voc candidates must have their stream in the same or an allied sector." if not is_hindi else "B.Voc/D.Voc उम्मीदवारों की स्ट्रीम समान या संबद्ध क्षेत्र में होनी चाहिए।",

    "priority_metric": "LEEP Priority Tier" if not is_hindi else "लीप प्राथमिकता स्तर",
    "matrix_metric": "Final Matrix Category" if not is_hindi else "अंतिम मैट्रिक्स श्रेणी",
    "outofstate_delta": "Quota Override Applied" if not is_hindi else "कोटा ओवरराइड लागू",

    "p_bter": "Priority 2: BTER Diploma" if not is_hindi else "प्राथमिकता 2: BTER डिप्लोमा",
    "p_raj_dip": "Priority 3: Raj. Domicile + Diploma" if not is_hindi else "प्राथमिकता 3: राज. मूल निवासी + डिप्लोमा",
    "p_out_dip": "Priority 4: Out-of-State + Diploma" if not is_hindi else "प्राथमिकता 4: आउट-ऑफ-स्टेट + डिप्लोमा",
    "p_raj_bsc": "Priority 5: Raj. Domicile + B.Sc." if not is_hindi else "प्राथमिकता 5: राज. मूल निवासी + B.Sc.",
    "p_out_bsc": "Priority 6: Out-of-State + B.Sc." if not is_hindi else "प्राथमिकता 6: आउट-ऑफ-स्टेट + B.Sc.",
    "p_raj_voc": "Priority 7: Raj. Domicile + Voc." if not is_hindi else "प्राथमिकता 7: राज. मूल निवासी + Voc.",
    "p_out_voc": "Priority 8: Out-of-State + Voc." if not is_hindi else "प्राथमिकता 8: आउट-ऑफ-स्टेट + Voc.",

    "out_warning": "⚠️ **Out-of-State Rule Applied:** Vertical and horizontal reservations are nullified. Eligible for Unreserved (GEN) seats only." if not is_hindi else "⚠️ **आउट-ऑफ-स्टेट नियम लागू:** ऊर्ध्वाधर और क्षैतिज आरक्षण निरस्त कर दिए गए हैं। केवल अनारक्षित (GEN) सीटों के लिए पात्र।",

    "projected_lists_title": "🏆 Projected Ranking Lists" if not is_hindi else "🏆 अनुमानित रैंकिंग सूचियां",
    "tiebreaker_seq_msg": "Candidate will be positioned in the following sequence pools:" if not is_hindi else "उम्मीदवार को निम्नलिखित अनुक्रमों (पूल) में स्थान दिया जाएगा:",
    "eff_academic_score": "Effective Merit Index" if not is_hindi else "प्रभावी मेरिट इंडेक्स",
    "based_on_qual": "(Based on Qualifying Exam)" if not is_hindi else "(अर्हक परीक्षा पर आधारित)",
    "pure_academic_caption": "Score based purely on qualifying examination." if not is_hindi else "विशुद्ध रूप से अर्हक परीक्षा पर आधारित स्कोर।",
    "download_report_btn": "📥 Download Official LEEP Report (PDF)" if not is_hindi else "📥 आधिकारिक लीप रिपोर्ट डाउनलोड करें (PDF)",
    "pdf_install_helper": "💡 To enable PDF downloads, install: `pip install fpdf2`" if not is_hindi else "💡 PDF डाउनलोड के लिए इंस्टॉल करें: `pip install fpdf2`"
}

# --- 3. DROP DOWN OPTIONS & BILINGUAL MAPS ---
qual_opts_en = ["Diploma in Engineering/Tech", "B.Sc. Degree", "B.Voc / 3-Yr D.Voc"]
qual_opts = qual_opts_en if not is_hindi else ["इंजीनियरिंग/तकनीकी में डिप्लोमा", "B.Sc. डिग्री",
                                               "B.Voc / 3-वर्षीय D.Voc"]

gender_options = ["M", "F", "Other"] if not is_hindi else ["M (पुरुष)", "F (महिला)", "Other (अन्य)"]
gender_map = {"M": "M", "M (पुरुष)": "M", "F": "F", "F (महिला)": "F", "Other": "Other", "Other (अन्य)": "Other"}

category_options = ["GEN", "OBC (Non-Creamy)", "SC", "ST", "MBC (Non-Creamy)", "EWS"] if not is_hindi else [
    "GEN (सामान्य)", "OBC (नॉन-क्रीमी लेयर)", "SC (अनुसूचित जाति)", "ST (अनुसूचित जनजाति)", "MBC (नॉन-क्रीमी लेयर)",
    "EWS (कमजोर वर्ग)"]
category_map = {"GEN": "GEN", "GEN (सामान्य)": "GEN", "OBC (Non-Creamy)": "OBC (Non-Creamy)",
                "OBC (नॉन-क्रीमी लेयर)": "OBC (Non-Creamy)", "SC": "SC", "SC (अनुसूचित जाति)": "SC", "ST": "ST",
                "ST (अनुसूचित जनजाति)": "ST", "MBC (Non-Creamy)": "MBC (Non-Creamy)",
                "MBC (नॉन-क्रीमी लेयर)": "MBC (Non-Creamy)", "EWS": "EWS", "EWS (कमजोर वर्ग)": "EWS"}

area_options = ["Non-TSP", "TSP"] if not is_hindi else ["गैर-टीएसपी (Non-TSP)", "टीएसपी (TSP)"]
area_map = {"Non-TSP": "Non-TSP", "गैर-टीएसपी (Non-TSP)": "Non-TSP", "TSP": "TSP", "टीएसपी (TSP)": "TSP"}

domicile_options = ["Rajasthan", "Outside Rajasthan"] if not is_hindi else ["राजस्थान (Rajasthan)",
                                                                            "राजस्थान से बाहर (Outside Rajasthan)"]
domicile_map = {"Rajasthan": "Rajasthan", "राजस्थान (Rajasthan)": "Rajasthan", "Outside Rajasthan": "Outside Rajasthan",
                "राजस्थान से बाहर (Outside Rajasthan)": "Outside Rajasthan"}

exs_options = ["None", "EXS1 (Killed in action)", "EXS2 (Disabled in action)", "EXS3 (Died in service)",
               "EXS4 (Disabled in service)", "EXS5 (Gallantry Awards)", "EXS6 (Wards of EXS)", "EXS7 (Wives of EXS)",
               "EXS8 (Wards of Serving)", "EXS9 (Wives of Serving)"]
sports_cat_options = ["None", "A (Absolute Priority)", "B", "C", "D", "E"]


# --- 4. OFFICIAL LOGO & NAVY BLUE HEADER STYLING ---
def get_base64_of_bin_file(bin_file):
    if os.path.exists(bin_file):
        with open(bin_file, 'rb') as f: return base64.b64encode(f.read()).decode()
    return ""


logo_base64 = get_base64_of_bin_file("CEGLogo.png")
logo_html = f'<img src="data:image/png;base64,{logo_base64}" class="header-logo">' if logo_base64 else ''

st.markdown(f"""
<style>
    .official-header {{ background: linear-gradient(135deg, #FFFFFF 0%, #F0F4F8 100%); padding: 20px 30px; border-radius: 12px; border-bottom: 4px solid {navy_blue}; border-top: 1px solid #E5E7EB; border-left: 1px solid #E5E7EB; border-right: 1px solid #E5E7EB; display: flex; align-items: center; justify-content: space-between; margin-bottom: 20px; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1); }}
    .header-text {{ display: flex; flex-direction: column; justify-content: center; }}
    .header-text h1 {{ font-family: 'Georgia', serif; font-weight: 800; margin: 0; margin-bottom: 5px; font-size: 2.6rem; color: {navy_blue} !important; line-height: 1.1; }}
    .header-text p {{ margin: 0; font-size: 1.1rem; letter-spacing: 1px; color: #4B5563 !important; font-weight: 600; }}
    .highlight {{ color: #D4AF37 !important; }}
    .header-logo {{ height: 100px; width: 100px; border-radius: 50%; object-fit: contain; }}
    div[data-baseweb="select"] > div:hover {{ border-color: {navy_blue} !important; }}
    .stTextInput input:focus, .stNumberInput input:focus, .stDateInput input:focus {{ border-color: {navy_blue} !important; box-shadow: 0 0 0 1px {navy_blue} !important; }}
    .stButton > button {{ background-color: {navy_blue} !important; color: #FFFFFF !important; border: none !important; transition: 0.2s; }}
    .stButton > button:hover {{ background-color: {navy_hover} !important; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.2); }}
    div[data-baseweb="checkbox"] input:checked + div {{ background-color: {navy_blue} !important; border-color: {navy_blue} !important; }}
    div[data-testid="stExpander"] {{ border-left: 4px solid {navy_blue} !important; }}
</style>
<div class="official-header"><div class="header-text"><h1>{T["app_title"]} <span class="highlight">2026</span></h1><p>{T["app_subtitle"]}</p></div>{logo_html}</div>
""", unsafe_allow_html=True)


def custom_metric(label, value, delta=None):
    delta_html = f"<div style='color: #4B5563; font-size: 1.05rem; margin-top: 8px; font-weight: 500;'>{delta}</div>" if delta else ""
    return f"""
    <div style="background-color: #FFFFFF; padding: 20px; border-radius: 12px; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1); border-top: 5px solid {navy_blue}; margin-bottom: 15px; border: 1px solid #E5E7EB;">
        <div style="font-size: 1.1rem; color: #6B7280; font-weight: 600; margin-bottom: 8px; text-transform: uppercase; letter-spacing: 0.5px;">{label}</div>
        <div style="font-size: 2.2rem; color: {navy_blue}; font-weight: 700; line-height: 1.2; word-wrap: break-word; white-space: pre-wrap;">{value}</div>
        {delta_html}
    </div>
    """


st.warning(f"**{T['disclaimer_title']}** {T['disclaimer_text']}")


# --- 5. PDF GENERATION ENGINE ---
def generate_pdf_report(data):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    navy, dark_gray, light_gray = (30, 58, 138), (55, 65, 81), (243, 244, 246)

    def clean_pdf_text(t):
        raw = str(t).replace('▲', '+').replace('✅', '').replace('🔹', '').replace('🛑', '').replace('⚠️', '').replace('✨',
                                                                                                                    '').replace(
            '🏅', '').strip()
        return raw.encode('latin-1', 'ignore').decode('latin-1')

    pdf.set_fill_color(*navy)
    pdf.rect(0, 0, 210, 42, 'F')
    pdf.set_text_color(255, 255, 255)
    pdf.set_font('Helvetica', 'B', 24)
    pdf.set_y(10)
    pdf.cell(0, 10, 'LEEP 2026', ln=True, align='C')
    pdf.set_text_color(212, 175, 55)
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(0, 6, 'LATERAL ENTRY ENGINEERING PROCESS - ELIGIBILITY REPORT', ln=True, align='C')
    pdf.ln(22)

    pdf.set_text_color(*navy)
    pdf.set_font('Helvetica', 'B', 15)
    pdf.cell(0, 10, 'TENTATIVE EVALUATION SUMMARY', ln=True)
    pdf.set_draw_color(*navy)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(5)

    pdf.set_text_color(*dark_gray)
    pdf.set_font('Helvetica', 'B', 11)
    pdf.cell(95, 7, 'CANDIDATE PROFILE', ln=False)
    pdf.cell(95, 7, 'ACADEMIC CREDENTIALS', ln=True)

    pdf.set_font('Helvetica', '', 10)
    pdf.cell(35, 6, 'Name:', ln=False)
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(50, 6, clean_pdf_text(data.get('name')), ln=False)
    pdf.set_font('Helvetica', '', 10)
    pdf.cell(35, 6, 'Qualification:', ln=False)
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(70, 6, clean_pdf_text(data.get('qual_exam')), ln=True)

    pdf.set_font('Helvetica', '', 10)
    pdf.cell(35, 6, 'Date of Birth:', ln=False)
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(50, 6, str(data.get('dob')), ln=False)
    pdf.set_font('Helvetica', '', 10)
    pdf.cell(35, 6, 'Domicile:', ln=False)
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(70, 6, clean_pdf_text(data.get('domicile')), ln=True)

    pdf.set_font('Helvetica', '', 10)
    pdf.cell(35, 6, 'Category & Gen:', ln=False)
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(50, 6, f"{clean_pdf_text(data.get('category'))} ({clean_pdf_text(data.get('gender'))})", ln=False)
    pdf.set_font('Helvetica', '', 10)
    pdf.cell(35, 6, 'Effective Score:', ln=False)
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(70, 6, f"{data.get('entered_perc', 0.0):.2f}", ln=True)
    pdf.ln(8)

    box_start_y = pdf.get_y()
    pdf.set_fill_color(*light_gray)
    pdf.rect(10, box_start_y, 190, 25, 'F')
    pdf.set_y(box_start_y + 3)
    pdf.set_font('Helvetica', 'B', 12)
    pdf.set_text_color(*navy)
    pdf.cell(0, 7, '   SIMULATION EVALUATION RESULTS', ln=True)
    pdf.set_font('Helvetica', '', 10)
    pdf.set_text_color(*dark_gray)
    pdf.cell(60, 6, '     LEEP Priority Tier:', ln=False)
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(130, 6, clean_pdf_text(data.get('display_priority')), ln=True)
    pdf.set_font('Helvetica', '', 10)
    pdf.cell(60, 6, '     Final Seat Matrix Category:', ln=False)
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(130, 6, clean_pdf_text(data.get('backend_category')), ln=True)

    pdf.set_y(box_start_y + 35)
    pdf.set_text_color(*navy)
    pdf.set_font('Helvetica', 'B', 13)
    pdf.cell(0, 8, 'PROJECTED TARGET RANKING COHORTS', ln=True)
    pdf.set_draw_color(*navy)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(4)
    pdf.set_font('Helvetica', 'B', 10)
    pdf.set_text_color(*dark_gray)
    for rank in data.get('ranks', []):
        pdf.cell(0, 6, f"- {clean_pdf_text(rank)}", ln=True)

    pdf.ln(6)
    pdf.set_fill_color(254, 243, 199)
    pdf.set_text_color(180, 83, 9)
    pdf.set_font('Helvetica', 'B', 8)
    pdf.cell(0, 6, 'OFFICIAL LEEP-2026 SYSTEM DISCLAIMER:', ln=True, fill=True)
    pdf.set_text_color(0, 0, 0)
    pdf.set_font('Helvetica', '', 7.5)
    disclaimer = "This Eligibility Simulator is provided for informational and guidance purposes only. The projected priority tiers, effective scores, and ranking lists generated by this tool are tentative and based entirely on the unverified data entered by the candidate. The final, official merit list and ranks will be generated by the Centre for Electronic Governance (CEG) during the actual LEEP-2026 Centralized Admission Process after thorough verification of original documents."
    pdf.multi_cell(0, 4, disclaimer, align='L', fill=True)

    return bytes(pdf.output())


# --- 6. INPUT LAYOUT (Dynamic & Reactive) ---
st.markdown(f"### {T['eval_details_header']}")

with st.expander(T["step1_title"], expanded=True):
    c1, c2, c3 = st.columns(3)
    with c1:
        name = st.text_input(T["cand_name"], "")
    with c2:
        dob = st.date_input(T["dob"], value=datetime(2005, 1, 1), min_value=datetime(1970, 1, 1),
                            max_value=datetime.today(), help=T["dob_help"])
    with c3:
        sel_qual = st.selectbox(T["qual_basis"], qual_opts)
        qual_exam_en = qual_opts_en[qual_opts.index(sel_qual)]

    st.markdown("---")

    c4, c5 = st.columns(2)
    with c4:
        entered_perc = st.number_input(T["perc_qual"], min_value=0.0, max_value=100.0, value=75.0, step=0.1,
                                       help=T["cutoff_help"])
    with c5:
        st.markdown("<br>", unsafe_allow_html=True)
        passed_bter, math_12th, allied_sector = False, False, False

        if qual_exam_en == "Diploma in Engineering/Tech":
            passed_bter = st.checkbox(T["passed_bter"], value=False)
        elif qual_exam_en == "B.Sc. Degree":
            math_12th = st.checkbox(T["math_12th"], value=False)
        else:  # B.Voc
            allied_sector = st.checkbox(T["allied_sector"], value=False)

with st.expander(T["step2_title"], expanded=True):
    st.info(T["priority_help"])

    cp1, cp2, cp3 = st.columns(3)
    with cp1:
        sel_domicile = st.selectbox(T["domicile"], domicile_options)
        domicile = domicile_map[sel_domicile]

    st.markdown("---")

    # --- PROACTIVE LOCKOUT UX TRIGGER ---
    km_quota = st.checkbox(T["km_label"], help=T["km_help"])
    is_locked_out = (domicile != "Rajasthan" or km_quota)

    if is_locked_out:
        st.warning(
            "⚠️ **Reservations Disabled:** Candidate is out-of-state or applying under Kashmiri Migrant quota." if not is_hindi else "⚠️ **आरक्षण अक्षम:** अभ्यर्थी आउट-ऑफ-स्टेट है या कश्मीरी प्रवासी कोटे के तहत आवेदन कर रहा है।")

    st.markdown("---")
    c7, c8 = st.columns(2)
    with c7:
        sel_gender = st.selectbox(T["gender"], gender_options)
        gender = gender_map[sel_gender]
    with c8:
        sel_category = st.selectbox(T["base_cat"], category_options, disabled=is_locked_out)
        category = category_map[sel_category]
        sel_area = st.selectbox(T["area"], area_options, disabled=is_locked_out)
        area = area_map[sel_area]

with st.expander(T["step3_title"], expanded=False):
    c9, c10 = st.columns(2)
    with c9:
        pwd_quota = st.checkbox(T["pwd_label"], disabled=is_locked_out)
        income_less_8l = st.checkbox(T["tfws_label"])  # TFWS is independent of state

    with c10:
        sel_exs = st.selectbox(T["exs_label"], exs_options, disabled=is_locked_out)
        exs_priority = sel_exs.split(" ")[0] if sel_exs != "None" and sel_exs != "कोई नहीं" else "None"

        sports_quota = st.checkbox(T["sports_label"], disabled=is_locked_out)
        sel_sports_cat = st.selectbox(T["sports_cat_label"], sports_cat_options,
                                      disabled=(not sports_quota or is_locked_out))
        sports_cat = sel_sports_cat.split(" ")[
            0] if sel_sports_cat != "None" and sel_sports_cat != "कोई नहीं" else "None"

    widow_quota, single_woman_quota = False, False
    if gender in ["F", "Other", "F (महिला)", "Other (अन्य)"]:
        st.markdown("---")
        cf1, cf2 = st.columns(2)
        with cf1: widow_quota = st.checkbox(T["widow_label"], disabled=is_locked_out)
        with cf2: single_woman_quota = st.checkbox(T["single_woman_label"], disabled=(widow_quota or is_locked_out))

st.markdown("<br>", unsafe_allow_html=True)
_, submit_btn_col2, _ = st.columns([1, 1, 1])
with submit_btn_col2:
    submitted = st.button(T["submit_btn"], use_container_width=True)

# --- 7. ALGORITHM EXECUTION & DASHBOARD ---
if submitted:
    st.toast(T["toast_done"], icon="✅")
    st.divider()
    st.markdown(f"## {T['dashboard_title']}")

    backend_category = category
    km_override_applied = False
    dom_override_applied = False

    # 1. Apply Lockout Category Wipe
    if km_quota:
        backend_category = "GEN"
        km_override_applied = True
    elif domicile != "Rajasthan":
        if backend_category != "GEN":
            backend_category = "GEN"
            dom_override_applied = True

    if is_locked_out:
        pwd_quota = False
        exs_priority = "None"
        area = "Non-TSP"
        sports_quota = False
        widow_quota = False
        single_woman_quota = False

    # --- ELIGIBILITY GATE ---
    # B.Voc passes automatically via allied sector check. B.Sc & Diploma require 45% (Gen) or 40% (Reserved)
    req_cutoff = 45.0 if category == "GEN" else 40.0
    is_eligible = True

    if qual_exam_en == "Diploma in Engineering/Tech":
        if entered_perc < req_cutoff:
            is_eligible = False
            st.error(f"{T['disq_cutoff']}\n\nRequired: {req_cutoff}%. Scored: {entered_perc}%.")

    elif qual_exam_en == "B.Sc. Degree":
        if not math_12th:
            is_eligible = False
            st.error(f"{T['disq_math']}\n\n{T['disq_math_msg']}")
        elif entered_perc < req_cutoff:
            is_eligible = False
            st.error(f"{T['disq_cutoff']}\n\nRequired: {req_cutoff}%. Scored: {entered_perc}%.")

    elif qual_exam_en == "B.Voc / 3-Yr D.Voc":
        if not allied_sector:
            is_eligible = False
            st.error(f"{T['disq_allied']}\n\n{T['disq_allied_msg']}")

    if is_eligible:
        # --- PRIORITY TIER MAPPING ---
        tier_str = ""
        if qual_exam_en == "Diploma in Engineering/Tech":
            if passed_bter:
                tier_str = T["p_bter"]
            elif domicile == "Rajasthan":
                tier_str = T["p_raj_dip"]
            else:
                tier_str = T["p_out_dip"]
        elif qual_exam_en == "B.Sc. Degree":
            tier_str = T["p_raj_bsc"] if domicile == "Rajasthan" else T["p_out_bsc"]
        else:  # B.Voc
            tier_str = T["p_raj_voc"] if domicile == "Rajasthan" else T["p_out_voc"]

        # SPORTS BONUS ADDITION
        effective_score = float(entered_perc)
        sports_bonus_applied = False
        sports_weight = 0.0
        cat_letter = "None"
        sports_a_triggered = False

        if sports_quota and sports_cat != "None":
            cat_letter = sports_cat
            if cat_letter == "A":
                sports_weight = 7.0
                sports_a_triggered = True
            elif cat_letter == "B":
                sports_weight = 7.0
            elif cat_letter == "C":
                sports_weight = 5.0
            elif cat_letter == "D":
                sports_weight = 4.0
            elif cat_letter == "E":
                sports_weight = 2.0

            effective_score += sports_weight
            sports_bonus_applied = True

        # --- UI OVERRIDE FOR SPORTS A ---
        base_display_priority = tier_str
        if sports_a_triggered:
            display_priority = "Priority 1: Sports A" if not is_hindi else "प्राथमिकता 1: Sports A"
        else:
            display_priority = base_display_priority

        dash_col1, dash_col2 = st.columns([1.5, 1])

        with dash_col1:
            c_m1, c_m2 = st.columns(2)
            with c_m1:
                st.markdown(custom_metric(T["priority_metric"], display_priority), unsafe_allow_html=True)
            with c_m2:
                delta_val = T["outofstate_delta"] if (dom_override_applied or km_override_applied) else None
                st.markdown(custom_metric(T["matrix_metric"], backend_category, delta_val), unsafe_allow_html=True)

            # Warnings Management
            if km_override_applied:
                km_warning = "⚠️ **Kashmiri Migrant Rule Applied:** Vertical and horizontal reservations are nullified. Eligible for Unreserved (GEN) seats." if not is_hindi else "⚠️ **कश्मीरी प्रवासी नियम लागू:** ऊर्ध्वाधर और क्षैतिज आरक्षण निरस्त कर दिए गए हैं। अनारक्षित (GEN) सीटों के लिए पात्र।"
                st.warning(km_warning)
            elif domicile != "Rajasthan":
                st.warning(T["out_warning"])

            # Sports A Dynamic Fallback Warning
            if sports_a_triggered:
                sports_a_msg_en = f"**Note:** Priority 1 (Sports A) is capped at 5% of total course seats. If candidate does not secure a Sports A seat, he/she will fall back to **{tier_str}** with an Effective Score of {effective_score:.2f}."
                sports_a_msg_hi = f"**नोट:** प्राथमिकता 1 (Sports A) कुल कोर्स सीटों के 5% तक ही सीमित है। यदि अभ्यर्थी Sports A सीट प्राप्त नहीं कर पाता है, तो वह **{tier_str}** पर वापस आ जाएगा, जिसमें प्रभावी स्कोर {effective_score:.2f} होगा।"
                st.info(sports_a_msg_hi if is_hindi else sports_a_msg_en)

            st.markdown(f"### {T['projected_lists_title']}")

            ranks = ["🔹 `leep_merit` (Overall State Merit)"]
            if gender in ["F", "F (महिला)"]: ranks.append("🔹 `leep_genf` (Overall General Female)")

            if backend_category != "GEN":
                clean_cat = backend_category.split(" ")[0].lower()
                ranks.append(f"🔹 `leep_{clean_cat}` (Category {backend_category})")
                if gender in ["F", "F (महिला)"]: ranks.append(
                    f"🔹 `leep_{clean_cat}f` (Category {backend_category} Female)")

            if backend_category == "ST" and area == "TSP":
                ranks.append("🔹 `leep_tsp` (TSP Quota)")

            if pwd_quota: ranks.append("🔹 `leep_pwd` (Persons with Special Ability - 5%)")
            if exs_priority != "None": ranks.append(f"🔹 `leep_exs` (Ex-Servicemen - {exs_priority})")
            if widow_quota: ranks.append("🔹 `leep_widow` (Widow/Divorced Quota)")
            if single_woman_quota: ranks.append("🔹 `leep_singlew` (Single Woman Dependent Quota)")

            if sports_quota and sports_cat != "None":
                if sports_a_triggered:
                    ranks.append(
                        "🔹 `leep_sports` (Priority: Sports A - Max 5% capacity, then falls back to Sports Category B)" if not is_hindi else "🔹 `leep_sports` (प्राथमिकता: Sports A - कुल सीटों के 5% तक सीमित, फिर Sports Category B पर वापस)")
                else:
                    ranks.append(f"🔹 `leep_sports` (Sports Category {sports_cat})")

            if km_quota: ranks.append("🔹 `leep_km` (Kashmiri Migrant Supernumerary Quota - 5%)")
            if income_less_8l: ranks.append("🔹 `leep_tfw` (Tuition Fee Waiver Scheme - 5%)")

            st.success(T["tiebreaker_seq_msg"])
            st.info("\n".join(ranks))

            if FPDF_AVAILABLE:
                pdf_payload = {
                    'name': name if name.strip() else "Candidate",
                    'dob': dob.strftime('%d-%m-%Y'),
                    'qual_exam': qual_exam_en,
                    'domicile': domicile_map[sel_domicile],
                    'entered_perc': effective_score,
                    'category': backend_category,
                    'gender': gender_map[sel_gender],
                    'display_priority': display_priority,
                    'backend_category': backend_category,
                    'ranks': ranks
                }
                try:
                    pdf_data = generate_pdf_report(pdf_payload)
                    st.download_button(label=T["download_report_btn"], data=pdf_data, file_name=f"LEEP_2026_Report.pdf",
                                       mime="application/pdf", use_container_width=True)
                except Exception as e:
                    st.error(f"Error compiling PDF: {e}")
            else:
                st.info(T["pdf_install_helper"])

        with dash_col2:
            gauge_full_title = f"{T['eff_academic_score']}<br><span style='font-size:14px;color:#6B7280'>{T['based_on_qual']}</span>"
            fig = go.Figure(go.Indicator(
                mode="gauge+number+delta" if sports_bonus_applied else "gauge+number",
                value=effective_score,
                delta={'reference': float(entered_perc), 'position': "top",
                       'valueformat': '.2f'} if sports_bonus_applied else None,
                domain={'x': [0, 1], 'y': [0, 1]},
                title={'text': gauge_full_title, 'font': {'size': 22, 'color': theme_axis_color}},
                number={'font': {'color': theme_axis_color}, 'valueformat': '.2f'},
                gauge={
                    'axis': {'range': [None, 110], 'tickwidth': 1, 'tickcolor': theme_axis_color,
                             'tickfont': {'color': theme_axis_color}},
                    'bar': {'color': navy_blue, 'thickness': 0.75},
                    'bgcolor': "rgba(0,0,0,0)",
                    'borderwidth': 2,
                    'bordercolor': "gray",
                    'steps': [
                        {'range': [0, req_cutoff], 'color': "rgba(239, 68, 68, 0.4)"},
                        {'range': [req_cutoff, 65], 'color': "rgba(191, 219, 254, 0.5)"},
                        {'range': [65, 110], 'color': "rgba(30, 58, 138, 0.3)"}],
                    'threshold': {'line': {'color': "#EF4444", 'width': 4}, 'thickness': 1, 'value': req_cutoff}
                }
            ))

            fig.update_layout(paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)", height=350,
                              margin=dict(l=20, r=20, t=110, b=20), font=dict(color=theme_axis_color))
            st.plotly_chart(fig, use_container_width=True, theme=chart_theme)

            if sports_bonus_applied:
                sports_bonus_caption_en = f"✨ Score includes **+{sports_weight} points** for Sports Category {cat_letter}."
                sports_bonus_caption_hi = f"✨ स्कोर में स्पोर्ट्स श्रेणी {cat_letter} के लिए **+{sports_weight} अंक** शामिल हैं।"
                st.caption(sports_bonus_caption_hi if is_hindi else sports_bonus_caption_en)
            else:
                st.caption(T["pure_academic_caption"])
